### ISSUE TITLE
securestorage problem

### ISSUE THREAD

**Issue by enlight3d** [wi3land/ionic-appauth-capacitor-demo#14]
Hello, I'm trying to implement your library into an app for a client. Seems working when I use angular dev's server (running npm start). But when I build for android using capacitor, I keep running into an error concerning "com.crypho.plugins.SecureStorage"  :

```
2020-06-17 16:44:52.121 16024-16424/com.eridanis.smartcitymobileapp W/System.err: java.lang.ClassNotFoundException: com.crypho.plugins.SecureStorage
2020-06-17 16:44:52.121 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at java.lang.Class.classForName(Native Method)
2020-06-17 16:44:52.121 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at java.lang.Class.forName(Class.java:453)
2020-06-17 16:44:52.121 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at java.lang.Class.forName(Class.java:378)
2020-06-17 16:44:52.121 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
2020-06-17 16:44:52.121 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
2020-06-17 16:44:52.121 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
2020-06-17 16:44:52.122 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:69)
2020-06-17 16:44:52.122 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:45)
2020-06-17 16:44:52.122 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2020-06-17 16:44:52.122 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:326)
2020-06-17 16:44:52.122 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at android.os.Looper.loop(Looper.java:181)
2020-06-17 16:44:52.122 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2020-06-17 16:44:52.123 16024-16424/com.eridanis.smartcitymobileapp W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.crypho.plugins.SecureStorage" on path: DexPathList[[zip file "/data/app/com.eridanis.smartcitymobileapp-f8HGqMN7THOUFr8iTJQ67g==/base.apk"],nativeLibraryDirectories=[/data/app/com.eridanis.smartcitymobileapp-f8HGqMN7THOUFr8iTJQ67g==/lib/arm64, /system/lib64, /system/vendor/lib64]]
2020-06-17 16:44:52.123 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
2020-06-17 16:44:52.123 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020-06-17 16:44:52.123 16024-16424/com.eridanis.smartcitymobileapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-06-17 16:44:52.123 16024-16424/com.eridanis.smartcitymobileapp W/System.err: 	... 12 more
2020-06-17 16:44:52.123 16024-16424/com.eridanis.smartcitymobileapp I/System.out: Error adding plugin com.crypho.plugins.SecureStorage.
2020-06-17 16:44:52.126 16024-16424/com.eridanis.smartcitymobileapp E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:69)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:45)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

When I run your demo, I get a different error btw :

```
2020-06-17 17:12:26.063 11057-11422/com.appauth.demo I/SecureStorage: Checking encryption keys failed.
    java.lang.Exception: KeyStore doesn't contain alias: com.appauth.demo.SecretStore
        at com.crypho.plugins.AbstractRSA.loadKey(AbstractRSA.java:75)
        at com.crypho.plugins.RSA.isEntryAvailable(RSA.java:24)
        at com.crypho.plugins.AbstractRSA.encryptionKeysAvailable(AbstractRSA.java:25)
        at com.crypho.plugins.SecureStorage.execute(SecureStorage.java:106)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:70)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

Could you help me out ?

Seems like it is linked to #11

**Comment by enlight3d** [comment]
Nevermind, I don't understand why, but I don't get anymore that error !
